[versions]
kotlin = "2.4.0"
agp = "9.1.0"

[libraries]
# Tests
test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
multiplatform-android = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
